# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stream_pb2 as stream__pb2


class StreamServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get = channel.unary_unary(
        '/stream.StreamService/get',
        request_serializer=stream__pb2.Request1.SerializeToString,
        response_deserializer=stream__pb2.Response1.FromString,
        )
    self.put = channel.unary_unary(
        '/stream.StreamService/put',
        request_serializer=stream__pb2.Request2.SerializeToString,
        response_deserializer=stream__pb2.Response2.FromString,
        )
    self.delete = channel.unary_unary(
        '/stream.StreamService/delete',
        request_serializer=stream__pb2.Request3.SerializeToString,
        response_deserializer=stream__pb2.Response3.FromString,
        )
    self.show = channel.unary_unary(
        '/stream.StreamService/show',
        request_serializer=stream__pb2.Request4.SerializeToString,
        response_deserializer=stream__pb2.Response4.FromString,
        )
    self.login = channel.unary_unary(
        '/stream.StreamService/login',
        request_serializer=stream__pb2.Request5.SerializeToString,
        response_deserializer=stream__pb2.Response5.FromString,
        )
    self.set_mode = channel.unary_unary(
        '/stream.StreamService/set_mode',
        request_serializer=stream__pb2.Request6.SerializeToString,
        response_deserializer=stream__pb2.Response6.FromString,
        )
    self.get_info = channel.unary_unary(
        '/stream.StreamService/get_info',
        request_serializer=stream__pb2.Request7.SerializeToString,
        response_deserializer=stream__pb2.Response7.FromString,
        )
    self.myshow = channel.unary_unary(
        '/stream.StreamService/myshow',
        request_serializer=stream__pb2.Request00.SerializeToString,
        response_deserializer=stream__pb2.Response00.FromString,
        )
    self.mychange = channel.unary_unary(
        '/stream.StreamService/mychange',
        request_serializer=stream__pb2.Request01.SerializeToString,
        response_deserializer=stream__pb2.Response01.FromString,
        )


class StreamServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def show(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def set_mode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_info(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def myshow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mychange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=stream__pb2.Request1.FromString,
          response_serializer=stream__pb2.Response1.SerializeToString,
      ),
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=stream__pb2.Request2.FromString,
          response_serializer=stream__pb2.Response2.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=stream__pb2.Request3.FromString,
          response_serializer=stream__pb2.Response3.SerializeToString,
      ),
      'show': grpc.unary_unary_rpc_method_handler(
          servicer.show,
          request_deserializer=stream__pb2.Request4.FromString,
          response_serializer=stream__pb2.Response4.SerializeToString,
      ),
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=stream__pb2.Request5.FromString,
          response_serializer=stream__pb2.Response5.SerializeToString,
      ),
      'set_mode': grpc.unary_unary_rpc_method_handler(
          servicer.set_mode,
          request_deserializer=stream__pb2.Request6.FromString,
          response_serializer=stream__pb2.Response6.SerializeToString,
      ),
      'get_info': grpc.unary_unary_rpc_method_handler(
          servicer.get_info,
          request_deserializer=stream__pb2.Request7.FromString,
          response_serializer=stream__pb2.Response7.SerializeToString,
      ),
      'myshow': grpc.unary_unary_rpc_method_handler(
          servicer.myshow,
          request_deserializer=stream__pb2.Request00.FromString,
          response_serializer=stream__pb2.Response00.SerializeToString,
      ),
      'mychange': grpc.unary_unary_rpc_method_handler(
          servicer.mychange,
          request_deserializer=stream__pb2.Request01.FromString,
          response_serializer=stream__pb2.Response01.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stream.StreamService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
